### ISSUE TITLE
Let debian-svp / svp run on an existing checkout

### ISSUE THREAD

**Issue by rhertzog** [jelmer/silver-platter#13]
Downloading packaging repositories can be time consuming, it would be nice if silver-platter was able to work on an existing checkout that we just hand over to the tool.

**Comment by jelmer** [comment]
silver-platter now supports "recipes", and I'm slowly working on migrating the logic for applying changes to separate binaries that don't necessarily live in silver-platter. 

The "debian-svp apply" command can be used to apply a "recipe" to a existing checkout. See the README for a description of the recipes.
