### ISSUE TITLE
"no changes made" success for svp run?

### ISSUE THREAD

**Issue by filippog** [jelmer/silver-platter#19]
Hello @jelmer,
I'm running `svp run` in CI in a schedule and ATM the jobs will fail even where no changes have been made, which might be ok in my case. I think the simplest fix might be to teach `svp run` to treat "no changes" (possibly other conditions as well) as non-errors via command line, what do you think ?

**Comment by jelmer** [comment]
Yeah, that's a good point. I wonder if we should mirror the behaviour of e.g. diff - An exit status of 0 means no differences were found, 1 means some differences were found, and 2 means trouble.

**Comment by filippog** [comment]
Mimicking diff sounds like a good idea to me! I'll give that a try

**Comment by filippog** [comment]
I realized that #21 doesn't really cover all cases, specifically `svp` calls `main()` and not via the if __name__ branch in `run.py`. I think an alternative would be to rename `main()` and have a new `main()` for the try/except wrapping, what do you think ?
