### ISSUE TITLE
support configurable commit address?

### ISSUE THREAD

**Issue by Smattr** [jelmer/silver-platter#23]
Not sure if it's appropriate to create this issue here or https://github.com/jelmer/janitor or if this is something Debian-Janitor-specific, so apologies in advance if this is the wrong place.

One of my repos received a PR from the Debian Janitor bot (very helpful, thank you!) and I noticed its commit has the author `root <root@bf0aeeb6f301>`. Does it make sense for this to be configurable and for the Debian Janitor to have this set to something meaningful? I'm just thinking when I look back on this commit in 10 years I'm going to have no idea who this user is/was.

**Comment by jelmer** [comment]
This should be fixed now - the issue was that the environment variables weren't preserved in the janitor when it invoked silver platter from a docker image.
