### ISSUE TITLE
jelmer.uk - Internal Server Error

### ISSUE THREAD

**Issue by jayvdb** [jelmer/silver-platter#5]
https://www.jelmer.uk/code/silver-platter is the only link in the metadata https://pypi.org/project/silver-platter/ and it returns

> Internal Server Error

**Comment by jelmer** [comment]
Thanks, fixed.

**Comment by jayvdb** [comment]
It has happened again.

**Comment by jelmer** [comment]
Fixed again, hopefully for good this time - the cron job that breaks it has been removed.

**Comment by jayvdb** [comment]
Thanks.

Worth noting that https://pypi.org/project/silver-platter/ doesnt include all of the urls which appear in `setup.py`.  My guess is that the upload was done with an older version of setuptools which didnt recognise `project_urls`.

https://pypi.org/project/subvertpy/ does include a "Download" link due to [`download_url`](https://github.com/jelmer/subvertpy/blob/987e965/setup.py#L432), but it is also pointing at your website instead of GitHub.  It would be a good idea to include a link to GitHub also as a backup.
